[package]
name = "fido-authenticator"
version = "0.0.0-unreleased"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-semihosting = "0.3.5"
ctap-types = { path = "../ctap-types" }
crypto-service = { path = "../crypto-service", default-features = false }
# embedded-hal = { version = "0.2", features = ["unproven"] }
serde = { version = "1.0", default-features = false }
# usbd-ctaphid = { git = "https://github.com/nickray/usbd-ctaphid", branch = "main", features = ["logging"] }
